variables:
  DOCKER_CF_INFO: "rockylinux"
  DOCKER_CF_TAG: "latest"

build-job:
  stage: build
  variables:
    DOCKER_CF_INFO: "rockylinux"
    DOCKER_CF_TAG: "9"
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    # - docker pull adobecoldfusion/coldfusion:latest-2021
    # - docker pull "$DOCKER_CF_INFO":"$DOCKER_CF_TAG"
    # echo "FROM $DOCKER_CF_INFO:$DOCKER_CF_TAG" >> dockerfile

    - |
      echo "FROM $DOCKER_CF_INFO:$DOCKER_CF_TAG" >> dockerfile

      echo "RUN dnf update -y && dnf install ca-certificates python3 git maven.noarch java-17-openjdk.x86_64 jq coreutils unzip -y --allowerasing " >> dockerfile
      echo "RUN curl -sSL -o /opt/fcli.tgz https://github.com/fortify/fcli/releases/download/latest/fcli-linux.tgz" >> dockerfile
      echo "RUN tar -xvzf /opt/fcli.tgz" >> dockerfile
      echo "RUN curl -sSL -o /opt/dod_certs.zip https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/unclass-certificates_pkcs7_DoD.zip" >> dockerfile
      echo "RUN cd /opt/; unzip -o dod_certs.zip" >> dockerfile
      echo "RUN find /opt/" >> dockerfile
      echo "RUN cp /opt/Certificates_PKCS7_v5_14_DoD/DoD_PKE_CA_chain.pem /etc/pki/ca-trust/source/anchors/" >> dockerfile
      echo "RUN update-ca-trust extract" >> dockerfile
       echo "COPY . /app" >> dockerfile
       echo "RUN find /app" >> dockerfile
       echo "WORKDIR /app" >> dockerfile
       echo "RUN cd /app && mvn clean && mvn package" >> dockerfile

    - docker build -t "$DOCKER_CF_INFO":"$DOCKER_CF_TAG" .

    - docker tag "$DOCKER_CF_INFO":"$DOCKER_CF_TAG" docker-registry.c2sf.mil/cmis/"$DOCKER_CF_INFO":latest
    - docker push docker-registry.c2sf.mil/cmis/"$DOCKER_CF_INFO":latest

# build-job-semgrep:
#   stage: build
#   variables:
#     DOCKER_CF_INFO: "returntocorp/semgrep"
#     DOCKER_CF_TAG: "latest"
#   before_script:
#     - mkdir -p $HOME/.docker
#     - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"
#     # - docker pull adobecoldfusion/coldfusion:latest-2021
#     # - docker pull "$DOCKER_CF_INFO":"$DOCKER_CF_TAG"
#     # echo "FROM $DOCKER_CF_INFO:$DOCKER_CF_TAG" >> dockerfile

#     - |
#        echo "FROM $DOCKER_CF_INFO:$DOCKER_CF_TAG" >> dockerfile_semgrep

#         echo "RUN apk update && apk upgrade && apk add git " >> dockerfile_semgrep

#     - docker build -f ./dockerfile_semgrep -t "$DOCKER_CF_INFO":"$DOCKER_CF_TAG" .

#     - docker tag "$DOCKER_CF_INFO":"$DOCKER_CF_TAG" docker-registry.c2sf.mil/cmis/"$DOCKER_CF_INFO":latest
#     - docker push docker-registry.c2sf.mil/cmis/"$DOCKER_CF_INFO":latest

test-job:
  stage: test
  image: docker-registry.c2sf.mil/cmis/$DOCKER_CF_INFO:latest
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - jq --version
    - wc --version
    - find /app
